import type { Metadata } from 'next';
import { cookies } from 'next/headers';
import { ReactNode } from 'react';
import { fontVariables } from '@app/fonts/index';
import { ThemeProvider } from '@app/providers/ThemeProvider';
import { ThemeScript } from '@app/providers/ThemeScript';
import { cn } from '@shared/lib/classNames';
import { parseThemeCookie, THEME_COOKIE_NAME } from '@shared/lib/themeCookie';
import { DARK_CLASS, ThemeMode } from '@shared/types/theme';

import '@app/styles/index.css';

export const metadata: Metadata = {
  title: 'keep-and-store',
  description: 'Generated by create next app'
};

export default async function RootLayout({ children }: { children: ReactNode }) {
  const cookieStore = await cookies();
  const themeCookie = cookieStore.get(THEME_COOKIE_NAME)?.value;
  const initialTheme = parseThemeCookie(themeCookie);

  return (
    <html
      lang="ru"
      suppressHydrationWarning
      className={cn(fontVariables, { [DARK_CLASS]: initialTheme.mode === ThemeMode.DARK })}
      data-theme={initialTheme.variant}
    >
      <head>
        <ThemeScript />
      </head>
      <body className="antialiased">
        <ThemeProvider initialTheme={initialTheme}>{children}</ThemeProvider>
      </body>
    </html>
  );
}
