import type { Metadata } from 'next';
import { ReactNode } from 'react';

import { fontVariables } from '@app/fonts/index';

import '@app/styles/index.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="ru" suppressHydrationWarning className={fontVariables}>
      <body className={`antialiased`}>{children}</body>
    </html>
  );
}
