import { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { hasLocale } from 'next-intl';
import { getMessages, setRequestLocale } from 'next-intl/server';
import { fontVariables } from '@app/fonts';
import { RootProvider } from '@app/providers/root-provider';
import { DEFAULT_LOCALE, routing } from '@shared/i18n/routing';
import { Header } from '@widgets/header/ui';
import '@app/styles/index.css';

export const generateStaticParams = (): Array<{ locale: string }> => {
  return routing.locales.map((locale) => {
    return { locale };
  });
};

export const metadata: Metadata = {
  title: 'keep-and-store',
  description: 'Generated by create next app'
};

const Layout = async (props: LayoutProps<'/[locale]'>) => {
  const { children, params } = props;
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  setRequestLocale(locale);

  const messages = await getMessages({ locale });

  return (
    <html lang={locale || DEFAULT_LOCALE} className={fontVariables} suppressHydrationWarning>
      <body className="antialiased">
        <RootProvider locale={locale} messages={messages}>
          <Header />
          {children}
        </RootProvider>
      </body>
    </html>
  );
};

export default Layout;
